
services:
  - type: web
    name: vibran-license-server
    env: node
    plan: free
    region: oregon
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: ADMIN_TOKEN
        generateValue: true
      - key: KEYS_FILE
        value: "/opt/render/project/src/keys.json"
